### PR TITLE
Use rpo v5 config

### PR DESCRIPTION
**Pull request by JFronny**
Updates the rpo config version to v5. This not only removes my nag messages but also fixes the translatable text in the pack overview since another language key was used for that previously.

### CODE REVIEW

**Comment by spiralhalo** [comment]
Interesting. Thanks for taking the initiative. What RPO version would this require so I can put a notice in the next release?

**Comment by JFronny** [comment]
Format v5 was introduced in 2.6.0, meaning only two versions for 1.17.1 don't support this, one of which was marked as a beta. I obviously recommend the latest version (2.7.1) though

**Comment by spiralhalo** [comment]
I see. I'm still trying to maintain 1.16 compatibility until the Frex API switch (which won't be 1.16 compatible either way). Not sure at what version to make the commitment to 1.17. These changes don't seem critical from what I gather?

**Comment by spiralhalo** [comment]
Although from how development goes, fixing light rays might be the last step before committing to POM implementation and toggleable passes which would require latest 1.17 Canvas. Current expectation is to commit to 1.17 from Lumi Lights version v0.32 onwards. I won't have any reason to not merge this by that point.

**Comment by JFronny** [comment]
v1 configs will be supported going forward for now, though v5 enables some fancy new features and some format simplifications

**Comment by spiralhalo** [comment]
Hm. Either way I'll merge this later for the 1.17 commitment release which is either v0.32 or v0.40. For the time being feel free to push more commits to the PR if necessary. Thanks again.

**Pull request merged**
