### PR TITLE
Important performance fix

### PR DESCRIPTION
**Pull request by supsm**
Some guy with no experience in glsl or java edition modding at all manages to fix a performance issue by adding 4 characters which were previously deleted

I have no idea what this does, all I know is that I can play at a decent framerate in fullscreen instead of 3 (without pbr ext ofc).

Yeet.

### CODE REVIEW

**Comment by Reeses-Puffs** [comment]
I think those might have been deleted for a good reason, but I'm not entirely sure

**Comment by supsm** [comment]
ik, but still. Just wanted to let awoo/spiralhalo/flair/kotatsuboi know that this is what was causing the performance issues i mentioned in the discord

**Comment by Reeses-Puffs** [comment]
there's a good chance that there might be a few other factors at play, and not just a few characters

**Comment by supsm** [comment]
I did my testing, adding those characters fixed performance for commit d3270a7 to match with previous commit

**Comment by spiralhalo** [comment]
Interesting observation!

**Pull request merged**
